### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pogcat09** [halotroop2288/VRCraft#2]
im not sure if this is just me, but i cant seem to load it with the fabric launcher
![mods screenshot](https://user-images.githubusercontent.com/85076493/120115523-a7fbc300-c149-11eb-970d-c357fee4fcff.jpg)

**Comment by halotroop2288** [comment]
OK.... You're not really supposed to. It's not finished. The only thing that's maybe finished is the server-side packet handling.
Also, that is definitely not how you load a mod. Learn the basics before making an issue about it.

**Comment by pogcat09** [comment]
oh sorry, my bad. i should've realized that it was a file folder instead of a java executable sooner
